baseURL = "http://example.org/"
languageCode = "en-us"
title = "Wir brauchen nicht so fortzuleben, wie wir gestern gelebt haben. Macht Euch nur von dieser Anschauung los und tausend Möglichkeiten laden uns zu neuem Leben ein. Christian Morgenstern"
theme = "hugoscroll"

